name: CI

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: "1.14.2"
      - uses: actions/checkout@v2
      - name: Run tests
        run: go test -tags=authprovider_gitlab ./...

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-18.04
    needs: tests
    steps:
      - uses: actions/checkout@v2
      - uses: jungwinter/split@v1
        id: splitRef
        with:
          msg: ${{ github.ref }}
          seperator: /
      - uses: jungwinter/split@v1
        id: splitRepository
        with:
          msg: ${{ github.repository }}
          seperator: /
      - name: Build and push Docker images
        run: |
          echo $GITHUB_TOKEN | docker login $REGISTRY_URL -u $GITHUB_USERNAME --password-stdin

          docker build --build-arg GO_TAGS=$GO_TAGS -t $REGISTRY_URL/$GITHUB_REPOSITORY/$IMAGE_NAME:$IMAGE_TAG .
          docker push $REGISTRY_URL/$GITHUB_REPOSITORY/$IMAGE_NAME:$IMAGE_TAG
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_USERNAME: ${{ steps.splitRepository.outputs._0 }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REGISTRY_URL: docker.pkg.github.com
          IMAGE_NAME: ${{ steps.splitRepository.outputs._1 }}
          IMAGE_TAG: gitlab-${{ steps.splitRef.outputs._2 }}
          GO_TAGS: authprovider_gitlab
